package com.qferiz.qferiztrafficinfo.fragments;


import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.widget.SwipeRefreshLayout;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.android.volley.AuthFailureError;
import com.android.volley.NetworkError;
import com.android.volley.NoConnectionError;
import com.android.volley.ParseError;
import com.android.volley.ServerError;
import com.android.volley.TimeoutError;
import com.android.volley.VolleyError;
import com.qferiz.qferiztrafficinfo.R;
import com.qferiz.qferiztrafficinfo.adapters.AdapterMovies;
import com.qferiz.qferiztrafficinfo.callbacks.UpcomingMoviesLoadedListener;
import com.qferiz.qferiztrafficinfo.database.MoviesDatabase;
import com.qferiz.qferiztrafficinfo.extras.Movie;
import com.qferiz.qferiztrafficinfo.extras.MovieSorter;
import com.qferiz.qferiztrafficinfo.extras.MyApplication;
import com.qferiz.qferiztrafficinfo.extras.SortListener;
import com.qferiz.qferiztrafficinfo.logging.L;
import com.qferiz.qferiztrafficinfo.task.TaskLoadUpcomingMovies;

import java.util.ArrayList;

/**
 * A simple {@link Fragment} subclass.
 * Use the {@link FragmentUpcoming#newInstance} factory method to
 * create an instance of this fragment.
 */
public class FragmentUpcoming extends Fragment implements SortListener, UpcomingMoviesLoadedListener, SwipeRefreshLayout.OnRefreshListener {

    //The key used to store arraylist of movie objects to and from parcelable
    private static final String STATE_MOVIES = "state_movies";
    //the arraylist containing our list of box office his
    private ArrayList<Movie> mListMovies = new ArrayList<>();
    //the adapter responsible for displaying our movies within a RecyclerView
    private AdapterMovies mAdapter;
    //the recyclerview containing showing all our movies
    private RecyclerView mRecyclerMovies;
    //the TextView containing error messages generated by Volley
    private TextView mTextError;
    //the sorter responsible for sorting our movie results based on choice made by the user in the FAB
    private MovieSorter mSorter = new MovieSorter();
    // Untuk men-SwipeRefreshLayout pada fragment
    private SwipeRefreshLayout mSwipeRefreshLayout;


    // TODO: Rename parameter arguments, choose names that match
    // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
//    private static final String ARG_PARAM1 = "param1";
//    private static final String ARG_PARAM2 = "param2";

    // TODO: Rename and change types of parameters
//    private String mParam1;
//    private String mParam2;


    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment FragmentUpcoming.
     */
    // TODO: Rename and change types and number of parameters
    public static FragmentUpcoming newInstance(String param1, String param2) {
        FragmentUpcoming fragment = new FragmentUpcoming();
        Bundle args = new Bundle();
//        args.putString(ARG_PARAM1, param1);
//        args.putString(ARG_PARAM2, param2);
        fragment.setArguments(args);
        return fragment;
    }

    public FragmentUpcoming() {
        // Required empty public constructor
    }

 /*   @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            mParam1 = getArguments().getString(ARG_PARAM1);
            mParam2 = getArguments().getString(ARG_PARAM2);
        }
    }*/

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View mView = inflater.inflate(R.layout.fragment_upcoming, container, false);
        mTextError = (TextView) mView.findViewById(R.id.textVolleyError);

        // SwipeRefreshLayout Animation Gesture
        mSwipeRefreshLayout = (SwipeRefreshLayout) mView.findViewById(R.id.swipeMovieUpcoming);
        mSwipeRefreshLayout.setColorSchemeResources(R.color.colorPrimary, R.color.colorAccent, R.color.colorAnimateSwipe1, R.color.colorAnimateSwipe2);
        mSwipeRefreshLayout.setOnRefreshListener(this);

        mRecyclerMovies = (RecyclerView) mView.findViewById(R.id.listMoviesUpcoming);

        //set the layout manager before trying to display data
        mRecyclerMovies.setLayoutManager(new LinearLayoutManager(getActivity()));
        mAdapter = new AdapterMovies(getActivity());
        mRecyclerMovies.setAdapter(mAdapter);

        if (savedInstanceState != null) {
            //if this fragment starts after a rotation or configuration change, load the existing movies from a parcelable
            mListMovies = savedInstanceState.getParcelableArrayList(STATE_MOVIES);

        } else {
            //if this fragment starts for the first time, load the list of movies from a database
            mListMovies = MyApplication.getWritableDatabase().readMovies(MoviesDatabase.UPCOMING);
            //if the database is empty, trigger an AsycnTask to download movie list from the web
            if (mListMovies.isEmpty()) {
                L.m("FragmentUpcoming: executing task from fragment");
                new TaskLoadUpcomingMovies(this).execute();
            }
        }

        //update your Adapter to containg the retrieved movies
        mAdapter.setMovies(mListMovies);
        return mView;
    }


    @Override
    public void onSortByName() {
//        L.t(getActivity(), "Sort Name Upcoming");
        mSorter.sortMoviesByName(mListMovies);
        mAdapter.notifyDataSetChanged();
    }

    @Override
    public void onSortByDate() {
//        L.t(getActivity(),"Sort Date Upcoming");
        mSorter.sortMoviesByDate(mListMovies);
        mAdapter.notifyDataSetChanged();
    }

    @Override
    public void onSortByRating() {
//        L.t(getActivity(),"Sort Rating Upcoming");
        mSorter.sortMoviesByRating(mListMovies);
        mAdapter.notifyDataSetChanged();
    }


    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        //save the movie list to a parcelable prior to rotation or configuration change
        outState.putParcelableArrayList(STATE_MOVIES, mListMovies);
    }

    private void handleVolleyError(VolleyError error) {
        //if any error occurs in the network operations, show the TextView that contains the error message
        mTextError.setVisibility(View.VISIBLE);
        if (error instanceof TimeoutError || error instanceof NoConnectionError) {
            mTextError.setText(R.string.error_timeout);

        } else if (error instanceof AuthFailureError) {
            mTextError.setText(R.string.error_auth_failure);
            //TODO
        } else if (error instanceof ServerError) {
            mTextError.setText(R.string.error_auth_failure);
            //TODO
        } else if (error instanceof NetworkError) {
            mTextError.setText(R.string.error_network);
            //TODO
        } else if (error instanceof ParseError) {
            mTextError.setText(R.string.error_parser);
            //TODO
        }
    }

    @Override
    public void onUpcomingMoviesLoaded(ArrayList<Movie> listMovies) {
        L.m("FragmentUpcoming: onUpcomingMoviesLoaded Fragment");

        if (mSwipeRefreshLayout.isRefreshing()) {
            mSwipeRefreshLayout.setRefreshing(false);
        }
        mAdapter.setMovies(listMovies);
    }

    @Override
    public void onRefresh() {
        L.t(getActivity(), "onRefresh Fragment Upcoming");
        //load the whole feed again on refresh, dont try this at home :)
        new TaskLoadUpcomingMovies(this).execute();
    }

}
